# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-ast
        name: check-ast
        description: Simply check whether files parse as valid python.
        stages: [pre-commit]
    -   id: check-added-large-files
        name: check-added-large-files
        description: Prevent giant files from being committed.
        stages: [pre-commit]
    -   id: check-json
        name: check-json
        description: Attempts to load all json files to verify syntax.
        stages: [pre-commit]
    -   id: check-yaml
        name: check-yaml
        description: Attempts to load all yaml files to verify syntax.
        stages: [pre-commit]
    -   id: check-toml
        name: check-toml
        description: Attempts to load all TOML files to verify syntax.
        stages: [pre-commit]
    -   id: trailing-whitespace
        name: trailing-whitespace
        description: Trims trailing whitespace.
        stages: [pre-commit]
    -   id: end-of-file-fixer
        name: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
        stages: [pre-commit]
    -   id: mixed-line-ending
        name: mixed-line-ending
        description: Replaces or checks mixed line ending.
        stages: [pre-commit]
    -   id: check-docstring-first
        name: check-docstring-first
        description: Checks for a common error of placing code before the docstring.
        stages: [pre-commit]
    -   id: debug-statements
        name: debug-statements
        description: Check for debugger imports and py37+ breakpoint() calls in python source.
        stages: [pre-commit]
    -   id: no-commit-to-branch
        name: no-commit-to-branch
        description: Protect specific branches from direct checkins.
        stages: [pre-commit]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.11.7'
  hooks:
    - id: ruff
      stages: [pre-commit]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort
        description: Sort imports
        stages: [pre-commit]
        args: [ "--profile", "black" ]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        name: flake8
        description: Code linter with flake8
        stages: [pre-commit]
        args:
        -   "--max-line-length=128"
        additional_dependencies:
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-simplify

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        name: mypy
        entry: poetry run mypy
        description: Python static type checker
        stages: [pre-commit]

-   repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    -   id: pycln
        name: pycln
        entry: poetry run pycln
        description: Remove unsed import statements
        stages: [pre-commit]
        args: [--all]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        name: pyupgrade
        description: Automatically upgrade syntax for newer versions of Python
        stages: [pre-commit]
        args: [--py39-plus]

-   repo: local
    hooks:

    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [ python ]
        stages: [pre-commit]
        args: ["--rcfile=.pylintrc"]
    -   id: pytest
        name: pytest
        description: Perform tests with pytest
        stages: [pre-push]
        entry: poetry run pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
